## TPA 插件配置文件
## Github：https://github.com/WarSkyGod/TPA

# 插件版本，请勿自行修改
version: 1.2

# 插件默认语言，自带 zh_CN 和 en_US，您也可以按照格式添加其他语言
lang: zh_CN

# 对方最晚可以在多长时间内接受？单位是秒
accept_delay: 30

# 传送前需要等待多长时间？单位是秒
teleport_delay: 3
